FROM registry.aliyuncs.com/slzcc/jenkins-slave-dind-java-maven
ADD script/slave.sh /home/jenkins/
COPY settings.xml /root/.m2/settings.xml
WORKDIR /home/jenkins
RUN rm -rf /usr/local/bin/docker && \
    curl -sSL get.docker.com https://get.docker.com/ | sh;
RUN curl -o /usr/local/docker-compse https://github.com/docker/compose/releases/download/1.11.2/docker-compose-Linux-x86_64 && \
    chmod +x /usr/local/docker-compse
ENV DOCKER_VERSION=1.13.1
