FROM fabric8/gogs:latest
ADD https://github.com/slzcc/DDC-Jenkins-CD/releases/download/v1.1/data.tar.gz /opt/gogs/
ADD https://github.com/slzcc/DDC-Jenkins-CD/releases/download/v1.1/git.tar.gz /home/
ADD start.sh /
